- defaults:
    link:
      create: true
      relink: true
- link:
    ~/.config/aliasrc: config/aliasrc
    ~/.config/du_excludes: config/du_excludes
    ~/.scripts:
    ~/.profile:
    ~/.bashrc:
- shell:
        - xkbcomp ~/.config/keyboard/xkbmap $DISPLAY; xmodmap ~/.config/keyboard/xmodmaprc
