- env:
    DATAPATH: /mnt/all/home/zzz
- link:
  ~/Downloads: $DATAPATH/Downloads
  ~/Videos: $DATAPATH/Videos
  ~/Pictures: $DATAPATH/Pictures
  ~/Documents: $DATAPATH/Documents
  ~/Music: $DATAPATH/Music
  ~/Music: $DATAPATH/Music
  ~/Desktop: $DATAPATH/Desktop
  ~/Documents: $DATAPATH/Documents
  ~/Downloads: $DATAPATH/Downloads
  ~/eclipse-workspace: $DATAPATH/eclipse
  ~/git: $DATAPATH/git
  ~/hiwi: $DATAPATH/hiwi
  ~/Mail: $DATAPATH/Mail
  ~/Music: $DATAPATH/Music
  ~/Notebooks: $DATAPATH/Notebooks
  ~/projects: $DATAPATH/projects
  ~/Public: $DATAPATH/Public
  ~/remote: $DATAPATH/remote
  ~/Scratch: $DATAPATH/Scratch
  ~/sDownload: $DATAPATH/sDownload
  ~/Studium: $DATAPATH/Studium
  ~/Templates: $DATAPATH/Templates
  ~/tmp: $DATAPATH/tmp
  ~/vmpv: $DATAPATH/vmpv
  ~/webtest: $DATAPATH/webtest
  ~/workspace: $DATAPATH/workspace
  ~/xdm-helper: $DATAPATH/xdm
  ~/.local/bin_shared: $DATAPATH/.local/bin_shared
  ~/.config/Code: $DATAPATH/.config/Code
