- defaults:
    link:
      create: true
      relink: true
      # force: true
- link:
    ~/.gitconfig:
    ~/.gitignore_global:
- shell:
  # the following have to run after linking ~/.gitconfig
  - git submodule update --init --recursive
  - git submodule sync --recursive


- clean: ['~', '~/.config']

- link:
    ~/.config/sxhkd/sxhkdrc: config/sxhkd/sxhkdrc
    ~/.config/coc/ultisnips: config/coc/ultisnips
    ~/.config/ranger/rifle.conf: config/ranger/rifle.conf
    ~/.config/ranger/rc.conf: config/ranger/rc.conf
    ~/.config/ranger/commands.py: config/ranger/commands.py
    ~/.config/rofi: config/rofi
    ~/.config/ranger/plugins/devicons.py: config/ranger/ranger_devicons/devicons.py
    ~/.config/ranger/plugins/devicons_linemode.py: config/ranger/ranger_devicons/devicons_linemode.py
    ~/.config/zathura/zathurarc: config/zathura/zathurarc
    ~/.config/xfce4/terminal/terminalrc: config/xfce4/terminalrc
    ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml: config/xfce4/xfce4-panel.xml
    ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml: config/xfce4/xfce4-power-manager.xml
    ~/.config/variety/variety.conf: config/variety/variety.conf
    ~/.config/variety/ui.conf : config/variety/ui.conf
    ~/.config/polybar/config: config/polybar/config
    ~/.config/polybar/launch.sh: config/polybar/launch.sh
    ~/.config/mpv/input.conf : config/mpv/input.conf
    ~/.config/mpv/mpv.conf : config/mpv/mpv.conf 
    ~/.config/mpv/install_plugins.sh : config/mpv/install_plugins.sh
    ~/.config/compton/compton.conf : config/compton/compton.conf
    ~/.config/cvim/cvimrc : config/cvim/cvimrc
    ~/.config/gtk-3.0 : config/gtk-3.0
    ~/.config/gtk-2.0 : config/gtk-2.0
    ~/.config/ncmpcpp: config/ncmpcpp
    ~/.config/dunst: config/dunst
    ~/.config/newsboat/urls: config/newsboat/urls
    ~/.config/newsboat/config: config/newsboat/config
    ~/.config/bmdirs: config/bmdirs
    ~/.config/bmfiles: config/bmfiles
    ~/.config/i3/config : config/i3/config
    ~/.config/i3blocks/config : config/i3blocks/config
    ~/.config/qutebrowser : config/qutebrowser
    ~/.config/calcurse : config/calcurse
    ~/.config/fontconfig : config/fontconfig
    ~/.config/mpd/mpd.conf : config/mpd/mpd.conf
    ~/.config/aliasrc: config/aliasrc
    ~/.config/redshift.conf: config/redshift.conf

    ~/.screenlayout : screenlayout
    # ~/.aria2/aria2.conf:
    # ~/.axelrc:
    # ~/.bash:
    ~/.bashrc:
    ~/.profile:
    ~/.bash_profile: profile
    ~/.zprofile: profile
    ~/.xprofile: profile
    ~/.scripts:
    ~/.vrapperrc: vrapperrc
    ~/.keynavrc: keynavrc
    # ~/.gnupg/gpg.conf:
    # ~/.haskeline:
    # ~/.hgrc:
    # ~/.inputrc:
    # ~/.ipython/profile_default/ipython_config.py: ipython/ipython_config.py
    # ~/.ipython/profile_default/ipython_kernel_config.py: ipython/ipython_kernel_config.py
    # ~/.ipython/profile_default/startup/disable_warnings.py: ipython/disable_warnings.py
    # ~/.irssi:
    # ~/.jupyter/jupyter_notebook_config.py: jupyter/jupyter_notebook_config.py
    # ~/.jupyter/nbconfig/notebook.json: jupyter/notebook.json
    # ~/.local/share/jupyter/nbextensions: jupyter/nbextensions
    # ~/.pythonrc:
    # ~/.rtorrent.rc:
    # ~/.shell:
    ~/.tmux.conf:
    # ~/.vim:
    # ~/.zsh:
    ~/.zshrc:
    ~/.Xdefaults:
    ~/.inputrc:
    ~/.xinitrc:
    ~/.emoji:
    ~/.fontawesome:
    ~/.icons:
    ~/.local/share/applications: local/share/applications

    ~/.config/mimeapps.list: config/mimeapps.list
    ~/.config/user-dirs.dirs: config/user-dirs.dirs
    ~/.config/vifm: config/vifm

- shell:
  # - mkdir -p ~/.rtorrent/session ~/.rtorrent/watch ~/.rtorrent/downloads

    # git cleanall -f
    # emacs.d/vendor/
    # irssi/scripts/vendor/
    # jupyter/nbextensions/
    # shell/plugins/
    # vim/bundle/
    # zsh/plugins/
  - ~/.scripts/tools/shortcuts
  # - xdg-mime default zathura.desktop application/pdf
  # - xdg-settings set default-web-browser qutebrowser.desktop
  - "[ ! -f ~/.fzf.zsh ] || [ ! -f ~/.fzf.bash ] && ~/.dotfiles/fzf/install"
  - "wget https://raw.githubusercontent.com/LaurenceWarne/qute-code-hint/master/code_select.py -O ~/.local/share/qutebrowser/userscripts/code_select.py"
  - "chmod +x ~/.local/share/qutebrowser/userscripts/code_select.py"
