- defaults:
    link:
      create: true
      relink: true
      # force: true
- link:
    ~/.gitconfig:
    ~/.gitignore_global:

- clean: ['~', '~/.config']

- link:
    ~/.config/variety/variety.conf: config/variety/variety.conf
    ~/.config/variety/ui.conf : config/variety/ui.conf
    ~/.config/polybar/config: config/polybar/config
    ~/.config/polybar/launch.sh: config/polybar/launch.sh
    ~/.config/sxhkd/sxhkdrc: config/sxhkd/sxhkdrc
    ~/.config/rofi: config/rofi
    ~/.config/zathura/zathurarc: config/zathura/zathurarc
    ~/.config/mpv/input.conf : config/mpv/input.conf
    ~/.config/mpv/mpv.conf : config/mpv/mpv.conf
    ~/.config/mpv/scripts : config/mpv/scripts
    ~/.config/mpv/install_plugins.sh : config/mpv/install_plugins.sh
    ~/.config/compton/compton.conf : config/compton/compton.conf
    ~/.config/gtk-3.0 : config/gtk-3.0
    ~/.config/gtk-2.0 : config/gtk-2.0
    ~/.config/dunst: config/dunst
    ~/.config/dirs.csv: config/dirs.csv
    ~/.config/files.csv: config/files.csv
    ~/.config/i3/config : config/i3/config
    ~/.config/i3blocks : config/i3blocks
    ~/.config/fontconfig : config/fontconfig
    ~/.config/networkmanager-dmenu/config.ini : config/networkmanager-dmenu/config.ini

    ~/.screenlayout : screenlayout
    # ~/.aria2/aria2.conf:
    # ~/.axelrc:
    # ~/.bash:
    ~/.profile:
    ~/.xprofile:
    ~/.scripts:
    # ~/.gnupg/gpg.conf:
    # ~/.haskeline:
    # ~/.hgrc:
    # ~/.inputrc:
    # ~/.ipython/profile_default/ipython_config.py: ipython/ipython_config.py
    # ~/.ipython/profile_default/ipython_kernel_config.py: ipython/ipython_kernel_config.py
    # ~/.ipython/profile_default/startup/disable_warnings.py: ipython/disable_warnings.py
    # ~/.irssi:
    # ~/.jupyter/jupyter_notebook_config.py: jupyter/jupyter_notebook_config.py
    # ~/.jupyter/nbconfig/notebook.json: jupyter/notebook.json
    # ~/.local/share/jupyter/nbextensions: jupyter/nbextensions
    # ~/.pythonrc:
    # ~/.rtorrent.rc:
    # ~/.shell:
    # ~/.vim:
    # ~/.zsh:
    ~/.Xdefaults:
    ~/.inputrc:
    ~/.xinitrc:
    ~/.config/emoji: config/emoji
    ~/.config/fontawesome: config/fontawesome
    ~/.icons:
    ~/.local/share/applications: local/share/applications

    ~/.config/mimeapps.list: config/mimeapps.list
    ~/.config/user-dirs.dirs: config/user-dirs.dirs
    ~/.config/vifm: config/vifm

- shell:
  # - mkdir -p ~/.rtorrent/session ~/.rtorrent/watch ~/.rtorrent/downloads

    # git cleanall -f
    # emacs.d/vendor/
    # irssi/scripts/vendor/
    # jupyter/nbextensions/
    # shell/plugins/
    # vim/bundle/
    # zsh/plugins/
  - ~/.scripts/tools/shortcuts
  # - xdg-mime default zathura.desktop application/pdf
  # - xdg-settings set default-web-browser qutebrowser.desktop
  - "[ -f ~/.fzf.zsh ] && [ -f ~/.fzf.bash ] || ~/.dotfiles/submodules/fzf/install"
  # - "git clone https://github.com/powerline/fonts /tmp/powerline_fonts; cd /tmp/powerline_fonts; ./install.sh"

