- env:
    DATAPATH: /mnt/all/home/zzz
    SDCARD: /media/sdcard
- link:
   ~/.zshrc:
   ~/Videos: $DATAPATH/Videos
   ~/Pictures: $DATAPATH/Pictures
   ~/Music: $SDCARD/Music
   ~/Desktop: $DATAPATH/Desktop
   ~/Documents: $DATAPATH/Documents
   ~/Downloads: $SDCARD/Downloads
   ~/eclipse-workspace: $DATAPATH/eclipse-workspace
   ~/git: $DATAPATH/git
   ~/hiwi: $DATAPATH/hiwi
   ~/Mail: $DATAPATH/Mail
   ~/Music: $DATAPATH/Music
   ~/Notebooks: $DATAPATH/Notebooks
   ~/projects: $DATAPATH/projects
   ~/Public: $DATAPATH/Public
   ~/remote: $DATAPATH/remote
   ~/softwares: $DATAPATH/softwares
   ~/Scratch: $DATAPATH/Scratch
   ~/sDownload: $DATAPATH/sDownload
   ~/Studium: $DATAPATH/Studium
   ~/Owncloud: $DATAPATH/Owncloud
   ~/Templates: $DATAPATH/Templates
   ~/tmp: $DATAPATH/tmp
   ~/vmpv: $DATAPATH/vmpv
   ~/webtest: $DATAPATH/webtest
   ~/workspace: $DATAPATH/workspace
   ~/xdm-helper: $DATAPATH/xdm-helper
   ~/.local/bin_shared: $DATAPATH/.local/bin_shared
   ~/.config/Code: $DATAPATH/.config/Code
