- defaults:
    link:
      create: true
      relink: true
      # force: true

- clean: ['~', '~/.config']

- link:
    ~/.config/qutebrowser : config/qutebrowser
    ~/.local/share/qutebrowser/userscripts: local/share/qutebrowser/userscripts
    ~/.local/share/qutebrowser/greasemonkey: local/share/qutebrowser/greasemonkey

- shell:
  - "wget https://raw.githubusercontent.com/LaurenceWarne/qute-code-hint/master/code_select.py -O ~/.local/share/qutebrowser/userscripts/code_select.py"
  - "chmod +x ~/.local/share/qutebrowser/userscripts/code_select.py"
