- defaults:
    link:
      create: true
      relink: true
      force: false
- link:
    ~/.config/ranger/rifle.conf: config/ranger/rifle.conf
    ~/.config/ranger/rc.conf: config/ranger/rc.conf
    ~/.config/ranger/jkl.conf: config/ranger/jkl.conf
    ~/.config/ranger/commands.py: config/ranger/commands.py
    ~/.config/ranger/plugins/devicons.py: config/ranger/ranger_devicons/devicons.py
    ~/.config/ranger/plugins/devicons_linemode.py: config/ranger/ranger_devicons/devicons_linemode.py
# - shell:
          # - [ cd ~/.local/share/fonts && wget "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DroidSansMono/complete/Droid%20Sans%20Mono%20Nerd%20Font%20Complete.otf"]
          # - [ cd /tmp; git clone https://github.com/alexanderjeurissen/ranger_devicons; cd ./ranger_devicons; make install ]
