- defaults:
    link:
      create: true
      relink: true
- link:
    ~/.config/aliasrc: config/aliasrc
    ~/.scripts:
    ~/.config/zsh/.zshrc: config/zsh/.zshrc
    ~/.zshenv: profile
    ~/.config/inputrc: config/inputrc
- shell:
        - xkbcomp ~/.config/keyboard/xkbmap $DISPLAY; xmodmap ~/.config/keyboard/xmodmaprc
