- defaults:
    link:
      create: true
      relink: true
- link:
    ~/.config/aliasrc: config/aliasrc
    ~/.scripts:
    ~/.zshrc:
    ~/.profile:
- shell:
        - xkbcomp ~/.config/keyboard/xkbmap $DISPLAY; xmodmap ~/.config/keyboard/xmodmaprc
