#!/bin/sh
alias ka="killall" \
	mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
	magit="nvim -c Magit" \
	a="sudo apt" \
	SS="sudo systemctl" \
	f="vifm" \
    r="ranger" \
	g="git" \
	trem="transmission-remote" \
	e="$EDITOR" \
	v="$EDITOR" \
	x="sxiv -ft *" \
	sdn="sudo shutdown -h now" \
	gua="git remote | xargs -L1 git push --all" \
	ls="ls -hN --color=auto --group-directories-first" \
	ls="lsd --group-dirs first" \
	la="ls -a" \
	l="ls -l" \
	lla="ls -la" \
	lt="ls --tree" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
	YT="youtube-viewer" \
	ref="shortcuts >/dev/null; source ~/.shortcuts" \
	upc="sudo pacman -Syu; pkill -RTMIN+8 i3blocks" \
	lsp="pacman -Qett --color=always | less"
	
alias cp="cp -i"                          # confirm before overwriting something
alias mv='mv -i'
alias df='df -h'                          # human-readable sizes
alias free='free -m'                      # show sizes in MB
alias suai='sudo apt install'
alias suar='sudo apt remove'
alias suau='sudo apt update'
alias suaU='sudo apt upgrade'

# export TERM=xterm-256color
alias py3=python3

alias open=xdg-open

# Mirror a website
alias mirrorsite='wget -m -k -K -E -e robots=off'
# Mirror stdout to stderr, useful for seeing data going through a pipe
alias peek='tee >(cat 1>&2)'


command -v nvim >/dev/null && alias vim="nvim" v="nvim" vimdiff="nvim -d" vd="nvim -d" # Use neovim for vim if present.

shdl() { curl -O $(curl -s http://sci-hub.tw/"$@" | grep location.href | grep -o http.*pdf) ;}
se() { du -a ~/.scripts/* ~/.config/* | awk '{print $2}' | fzf | xargs  -r $EDITOR ;}
sv() { vcopy "$(du -a ~/.scripts/* ~/.config/* | awk '{print $2}' | fzf)" ;}
vf() { fzf | xargs -r -I % $EDITOR % ;}

