#!/bin/bash

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# Fix Gnome Apps Slow  Start due to failing services
# Add this when you include flatpak in your system
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY
dbus-update-activation-environment --all

[[ -f ~/.zshenv ]] && source ~/.zshenv

xrdb ~/.Xdefaults &
remaps &	# run the remaps script, switching caps/esc and more; check it for more info

autorandr -c &
blueman-applet &
compton --config ~/.config/compton/compton.conf &
dunst &
calendar &
mail &
gnome-screensaver &
gxkb &
keynav &
nm-applet &
qutebrowser &
# setbg &
st &
sxhkd &
telegram-desktop &
udiskie -t & # automount
unclutter & # mouse invinsible
xfce4-power-manager &
xset r rate 300 50 &	# Speed xrate up
([[ $(cat /etc/hostname) =~ kellerberg|heidenpeters|manjaro|mythos|frankfurter ]] || xmodmap -e "pointer = 3 2 1") &
([[ $(cat /etc/hostname) =~ kellerberg|heidenpeters|manjaro|mythos ]] && feh --bg-fill .config/wall.jpg ) &

#  podentr &

# This is the list for lf icons:
export LF_ICONS="di=📁:\
fi=📃:\
tw=🤝:\
ow=📂:\
ln=⛓:\
or=❌:\
ex=🎯:\
*.txt=✍:\
*.mom=✍:\
*.me=✍:\
*.ms=✍:\
*.png=🖼:\
*.ico=🖼:\
*.jpg=📸:\
*.jpeg=📸:\
*.gif=🖼:\
*.svg=🗺:\
*.xcf=🖌:\
*.html=🌎:\
*.xml=📰:\
*.gpg=🔒:\
*.css=🎨:\
*.pdf=📚:\
*.djvu=📚:\
*.epub=📚:\
*.csv=📓:\
*.xlsx=📓:\
*.tex=📜:\
*.md=📘:\
*.r=📊:\
*.R=📊:\
*.rmd=📊:\
*.Rmd=📊:\
*.mp3=🎵:\
*.opus=🎵:\
*.ogg=🎵:\
*.m4a=🎵:\
*.flac=🎼:\
*.mkv=🎥:\
*.mp4=🎥:\
*.webm=🎥:\
*.mpeg=🎥:\
*.zip=📦:\
*.rar=📦:\
*.7z=📦:\
*.tar.gz=📦:\
*.z64=🎮:\
*.v64=🎮:\
*.n64=🎮:\
*.1=ℹ:\
*.nfo=ℹ:\
*.info=ℹ:\
*.log=📙:\
*.iso=📀:\
*.img=📀:\
*.bib=🎓:\
*.ged=👪:\
*.part=💔:\
*.torrent=🔽:\
"
