config.bind(",h", "set downloads.location.directory \"~/\" ;; hint links download")
config.bind(",.d", "set downloads.location.directory \"~/.dotfiles\" ;; hint links download")
config.bind(",.c", "set downloads.location.directory \"~/.config\" ;; hint links download")
config.bind(",D", "set downloads.location.directory \"~/Documents\" ;; hint links download")
config.bind(",d", "set downloads.location.directory \"~/Downloads\" ;; hint links download")
config.bind(",a", "set downloads.location.directory \"~/hiwi/ACPLT-DevKit-linux64/acplt\" ;; hint links download")
config.bind(",ad", "set downloads.location.directory \"~/hiwi/ACPLT-DevKit-linux64/acplt/dev\" ;; hint links download")
config.bind(",M", "set downloads.location.directory \"~/Music\" ;; hint links download")
config.bind(",P", "set downloads.location.directory \"~/Pictures\" ;; hint links download")
config.bind(",V", "set downloads.location.directory \"~/Videos\" ;; hint links download")
config.bind(",S", "set downloads.location.directory \"~/.dotfiles/shortcut-sync\" ;; hint links download")
config.bind(",c", "set downloads.location.directory \"~/.config\" ;; hint links download")
config.bind(",sb", "set downloads.location.directory \"~/Owncloud/Studium/ws18/Berechenbarkeit und Komplexität\" ;; hint links download")
config.bind(",sa", "set downloads.location.directory \"~/Owncloud/Studium/ws18/Automatic Speech Recognition\" ;; hint links download")
config.bind(",sn", "set downloads.location.directory \"~/Owncloud/Studium/ws18/Numerisches Rechnen\" ;; hint links download")
config.bind(",sc", "set downloads.location.directory \"~/Owncloud/Studium/ws18/Compilerbau\" ;; hint links download")
config.bind(",ss", "set downloads.location.directory \"~/Owncloud/Studium/ws18/Softwaretechnik\" ;; hint links download")
