#!/bin/bash

if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
   arandr
fi

HDMI1='HDMI1'
edp='eDP1'

xrandrOut=$(xrandr)

hdmiName=$(echo "${xrandrOut}" | grep -i '${HDMI1}' | awk '{print $1}')
edpName=$(echo "${xrandrOut}" | grep -i '${edp}' | awk '{print $1}')

activeDisplays=$(echo "${xrandrOut}" | grep " connected" | sed -e "s/\([A-Z0-9]\+\) connected.*/\1/" | tr -s '\n' ' ')
displayFile='/tmp/.displays'

if [[ -f "${displayFile}" ]]; then
    oldDisplays=$(cat "${displayFile}")
else
    oldDisplays=""
fi

if [[ "${oldDisplays}" != "${activeDisplays}" ]]; then
    change="yes"
else
    change="no"
fi

#External, HDMI
if [[ "$activeDisplays" =~ "${hdmiName}" ]]; then
  if [[ "${change}" = "yes" ]]; then
    # $(xrandr --output "${edpName}" --off)
    # $(xrandr --output "${hdmiName}" --primary --auto)
    bash ~/.screenlayout/home.sh
  fi
  echo "HDMI"
  echo "HDMI"
  echo ""
  
#Only one internal
elif [[ "$activeDisplays" =~ "${edpName}" ]]; then
  if [[ "${change}" = "yes" ]]; then
    bash ~/.screenlayout/panda.sh
  fi
  echo "eDP"
  echo "eDP"
  echo ""
fi

if [[ "${change}" = "yes" ]]; then
  echo "${activeDisplays}" > "${displayFile}"
fi
