#!/bin/bash

update(){
  xrandrOut=$(xrandr)

  hdmiName=$(echo "${xrandrOut}" | grep -i 'HDMI1' | awk '{print $1}')
  hdmiResolution=$(xrandr-tool resolution ${hdmiName} | head -n1)
  edpName=$(echo "${xrandrOut}" | grep -i 'EDP' | awk '{print $1}')

  activeDisplays=$(echo "${xrandrOut}" | grep " connected" | sed -e "s/\([A-Z0-9]\+\) connected.*/\1/" | tr -s '\n' ' ')
  displayFile='/tmp/.displays'

  if [[ -f "${displayFile}" ]]; then
    oldDisplays=$(cat "${displayFile}")
  else
    oldDisplays=""
  fi

  if [[ "${oldDisplays}" != "${activeDisplays}" ]]; then
    change="yes"
  else
    change="no"
  fi

# External, HDMI
  if [[ "$activeDisplays" =~ "${hdmiName}" ]]; then
    if [[ "${hdmiResolution}" == "2560x1080" ]]; then
      $(~/.screenlayout/home.sh)
    elif [[ "${hdmiResolution}" == "1920x1080" ]]; then
      $(~/.screenlayout/fat.sh)
    elif [[ "${hdmiResolution}" == "1680x1050" ]]; then
      $(~/.screenlayout/job2.sh)
    else
      $(xrandr --output ${hdmiName} --primary --auto --output eDP1 --auto)
    fi
    echo "HDMI"
    echo "HDMI"
    echo ""

    # Only one internal
  elif [[ "$activeDisplays" =~ "${edpName}" ]]; then
  # if [[ "${change}" = "yes" ]]; then
    $(xrandr --output "${edpName}" --primary --auto)
    # $(~/.screenlayout/panda.sh)
  # fi
    echo "eDP"
    echo "eDP"
    echo ""
  fi

  if [[ "${change}" = "yes" ]]; then
    echo "${activeDisplays}" > "${displayFile}"
  fi
}

if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  update
fi

update
