#!/bin/sh

transmission-remote -l 2>&1 | grep % |
  sed " # This first sed command is to ensure a desirable order with sort
  s/.*Stopped.*/A/g;
  s/.*Seeding.*/Z/g;
  s/.*100%.*/N/g;
  s/.*Idle.*/B/g;
  s/.*Uploading.*/L/g;
  s/.*%.*/M/g" |
    sort -h | uniq -c | sed " # Now we replace the standin letters with icons.
        s/A/%{F#0f0}🛑%{F-}/g;
        s/B/⌛️/g;
        s/L/🔼/g;
        s/M/🔽/g;
        s/N/%{F#f00}✅%{F-}/g;
        s/Z/%{F#f00}🌱%{F-}/g" | awk '{print $2, $1}' | tr '\n' ' ' | sed -e "s/ $//g"
echo
        

case $BLOCK_BUTTON in
    1) $TERMINAL -e tremc ;;
    3) pgrep -x dunst >/dev/null && notify-send "<b>Torrent module:</b>
🛑: paused
⏳: idle (seeds needed)
🔼: uploading (unfinished)
🔽: downloading
✅: done
🌱: done and seeding" ;;
esac

