#!/bin/sh
xrandr --output HDMI2 --off --output HDMI-1 --mode 1920x1080 --primary --pos 0x0 --rotate normal --output DP1 --off --output eDP-1 --mode 1368x768 --pos 1920x312 --rotate normal --output VIRTUAL1 --off
