#!/bin/sh
xrandr --output HDMI-2 --off --output HDMI-1 --primary --mode 1920x1080 --pos 1368x0 --rotate normal --output DP1 --off --output eDP-1 --mode 1368x768 --pos 0x312 --rotate normal --output VIRTUAL1 --off
