#!/usr/bin/env bash

if [ "$#" -gt 1 ]; then
  echo "usage: extbacklight [value]"
  exit 1
elif [ "$#" -eq 1 ]; then
  sudo /usr/bin/ddcutil setvcp 10 $1
  exit 0
fi
value=$(rofi -dmenu -l 0 -width -17 -p Brightness in % -theme blue)
sudo /usr/bin/ddcutil setvcp 10 $value
xbacklight $value
