#!/usr/bin/env sh

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -x polybar >/dev/null; do sleep 1; done

# for i in $(polybar -m | awk -F: '{print $1}'); do MONITOR=$i polybar -c ~/.config/polybar/config_1 white & done

export MONITOR=$(polybar -m | tail -1 | sed -e 's/:.*$//g')
polybar -c ~/.config/polybar/config_1 white &

echo "Bars launched..."
