#!/usr/bin/bash

file=$HOME/Music/$(mpc --format %file% current)

function del_current() {
  #function_body
  notify-send "Removing" "$file"
  mpc del 0
  rm "$file"
  mpc update
}

case "$1" in
  d*) del_current;;
  i*) ffmpeg -y -i "$file" /tmp/mpd_cover_tmp.jpg ;;
  *) cat << EOF
lmc: cli music interface for mpd and pulse for those with divine intellect too
grand to remember the mpc/pamixer commands.

Allowed options:
  up NUM  Increase volume (2 secs default)
  down NUM  Decrease volume (2 secs default)
  mute    Toggle mute
  truemute  Mute
  next    Next track
  prev    Previous track
  toggle  Toggle pause
  truepause Pause
  foward NUM  Seek foward in song (2 secs default)
  back NUM  Seek back in song (2 secs default)
  restart Restart current song
  all else  Print this message

All of these commands, except for \`truemute\`, \`prev\` and \`play\` can be truncated,
i.e. \`lmc r\` for \`lmc restart\`.
EOF
esac

