#!/usr/bin/env python
import copy
import sys
import math
import PyPDF2

def split_pages(src, dst):
    m = {'l':10, 'u':10, 'r':20, 'd':15}
    src_f = open(src, 'r+b')
    dst_f = open(dst, 'w+b')

    input = PyPDF2.PdfFileReader(src_f)
    output = PyPDF2.PdfFileWriter()
    current = 1

    for i in range(input.getNumPages()):
        p = input.getPage(i)
        x1, x2 = p.mediaBox.lowerLeft
        x3, x4 = p.mediaBox.upperRight
        p.mediaBox.upperRight = x3*2, x4
        output.addPage(p)
        #  output.addBlankPage()

    output.write(dst_f)

    #  output1.write(dst_f)
    src_f.close()
    dst_f.close()

input_file = sys.argv[1]
output_file = sys.argv[2]

split_pages(input_file, output_file)
