#!/bin/bash
post="_$1"
if [[ "$1" == "" ]]; then
  post="_def"
fi

export RANGER_LEVEL=
cd ${HOME}
# This script is called by i3 on startup to remap keys.
# Increase key speed via a rate change
# setxkbmap de
xset r rate 300 50
# Map the caps lock key to super...
# setxkbmap -option caps:super
xkbcomp -w 0 ~/.config/keyboard/xkbmap${post} $DISPLAY; xmodmap ~/.config/keyboard/xmodmaprc
# But when it is pressed only once, treat it as escape.
killall xcape 2>/dev/null;
if [[ ! $post == "_def" ]]; then
  xcape -e 'Super_L=Escape;Control_L=ISO_Level3_Shift|Shift_L|p'
fi
#setxkbmap -layout u s,mn -variant altgr-intl, -option grp:rctrl_rshift_toggle
i3 'reload'
restart sxhkd
xinput set-prop $(xinput | grep SynPS | awk '{print $6}' | awk -F '=' '{print $2}') "libinput Tapping Enabled" 1
