#!/bin/bash
# Output locations. Unactivated progs should go to /dev/null.
shell_shortcuts="$HOME/.shortcuts"
ranger_shortcuts="$HOME/.config/ranger/shortcuts.conf"
qute_shortcuts="$HOME/.config/qutebrowser/shortcuts.py"
fish_shortcuts="/dev/null"
vifm_shortcuts="$HOME/.config/vifm/vifmshortcuts"

# Remove, prepare files
rm -f "$ranger_shortcuts" "$qute_shortcuts" 2>/dev/null
printf "# vim: filetype=sh\\n" > "$fish_shortcuts"
printf "# vim: filetype=sh\\n" > "$shell_shortcuts"
printf "\" vim: filetype=vim\\n" > "$vifm_shortcuts"

# Format the `bmdirs` file in the correct syntax and sent it to all three configs.
sed "s/\s*#.*$//;/^\s*$/d" "$HOME/.config/bmdirs" | tee >(awk '{tmp=$1; $1 = ""; print "alias ,"tmp"=\"cd \\\""$0"\\\" && ls -a\""}' | sed 's/ ~/$HOME/'>> $shell_shortcuts) \
	>(awk '{tmp=$1; $1 = ""; print "config.bind(\","tmp"\", \"set downloads.location.directory \\\""$0"\\\" ;; hint links download\")"}' | sed 's/ ~/~/' >> "$qute_shortcuts") \
	>(awk '{tmp=$1; $1=""; print "map ,"tmp" cd "$0"\nmap t"tmp" tab_new "$0}' >> "$ranger_shortcuts")\
	>(awk '{tmp=$1; $1=""; print "map m"tmp" chain cut; cd "$0"; paste; cd -"}'>> "$ranger_shortcuts" )\
	>(awk '{tmp=$1; $1=""; print "map Y"tmp" chain copy; cd "$0"; paste; cd -"}'>> "$ranger_shortcuts")
	# >(awk '{print "abbr", $1, "\"cd " $2 "; and ls -a\""}' >> "$fish_shortcuts") \
	# >(awk '{print "map g" $1, ":cd", $2 "<CR>\nmap t" $1, "<tab>:cd", $2 "<CR><tab>\nmap M" $1, "<tab>:cd", $2 "<CR><tab>:mo<CR>\nmap Y" $1, "<tab>:cd", $2 "<CR><tab>:co<CR>" }' >> "$vifm_shortcuts") \
# Format the `configs` file in the correct syntax and sent it to both configs.
sed "s/\s*#.*$//;/^\s*$/d"  "$HOME/.config/bmfiles" | tee >(awk '{print "alias "$1"=\"$EDITOR "$2"\""}' >> "$shell_shortcuts") \
	>(awk '{print "map "$1" shell $EDITOR "$2}' >> "$ranger_shortcuts")
	# >(awk '{print "abbr", $1, "\"$EDITOR "$2"\""}' >> "$fish_shortcuts") \
	# >(awk '{print "map", $1, ":e", $2 "<CR>" }' >> "$vifm_shortcuts") \
