#!/bin/bash
# Output locations. Unactivated progs should go to /dev/null.
shell_shortcuts="$HOME/.shortcuts"
ranger_shortcuts="$HOME/.config/ranger/shortcuts.conf"
qute_shortcuts="$HOME/.config/qutebrowser/shortcuts.py"
fish_shortcuts="/dev/null"
vifm_shortcuts="$HOME/.config/vifm/vifmshortcuts"

# Remove, prepare files
rm -f "$ranger_shortcuts" "$qute_shortcuts" 2>/dev/null
printf "# vim: filetype=sh\\n" > "$fish_shortcuts"
printf "# vim: filetype=sh\\nalias " > "$shell_shortcuts"
printf "\" vim: filetype=vim\\n" > "$vifm_shortcuts"

# Format the `directories` file in the correct syntax and sent it to all three configs.
sed "s/\s*#.*$//;/^\s*$/d" "$HOME/.config/dirs.csv" | tee >(awk -F'\t' '{print "g"$1"=\"cd \\\""$2"\\\" && ls -a\" \\"}' | sed 's/cd \\"~/cd \\"$HOME/'>> $shell_shortcuts) \
	>(awk -F'\t' '{print "config.bind(\","$1"\", \"set downloads.location.directory \\\""$2"\\\" ;; hint links download\")"}' >> "$qute_shortcuts") \
	>(awk -F'\t' '{print "map g"$1" cd "$2"\nmap t"$1" tab_new "$2}' >> "$ranger_shortcuts")\
	>(awk -F'\t' '{print "map mv"$1" chain cut; cd "$2"; paste; cd -"}'>> "$ranger_shortcuts" )\
	>(awk -F'\t' '{print "map cp"$1" chain copy; cd "$2"; paste; cd -"}'>> "$ranger_shortcuts")
	# >(awk '{print "abbr", $1, "\"cd " $2 "; and ls -a\""}' >> "$fish_shortcuts") \
	# >(awk '{print "map g" $1, ":cd", $2 "<CR>\nmap t" $1, "<tab>:cd", $2 "<CR><tab>\nmap M" $1, "<tab>:cd", $2 "<CR><tab>:mo<CR>\nmap Y" $1, "<tab>:cd", $2 "<CR><tab>:co<CR>" }' >> "$vifm_shortcuts") \
# Format the `configs` file in the correct syntax and sent it to both configs.
sed "s/\s*#.*$//;/^\s*$/d"  "$HOME/.config/files.csv" | tee >(awk '{print $1"=\"$EDITOR "$2"\" \\"}' >> "$shell_shortcuts") \
	>(awk '{print "map "$1" shell $EDITOR "$2}' >> "$ranger_shortcuts")
	# >(awk '{print "abbr", $1, "\"$EDITOR "$2"\""}' >> "$fish_shortcuts") \
	# >(awk '{print "map", $1, ":e", $2 "<CR>" }' >> "$vifm_shortcuts") \
