#!/usr/bin/sh

notify-send "VPN toggle"
interface=${1:vpn-default}
notify-send $interface
if nmcli con show --active | grep -q "tun0"; then
    status=$(nmcli con down "$interface")
else
    status=$(nmcli con up "$interface")
fi
notify-send "VPN toggle" "$status"

pkill -RTMIN+13 i3blocks
