#!/usr/bin/sh

notify-send "VPN toggle"
interface=${1:vpn-default}
notify-send $interface
if ifconfig tun0 | grep -q "00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00"; then
    status=$(nmcli con down "$interface")
else
    status=$(nmcli con up "$interface")
fi
notify-send "VPN toggle" "$status"

pkill -RTMIN+13 i3blocks
