#!/bin/bash

notify-send 'yt'
youtube-dl --download-archive ~/Music/downloaded.txt --no-post-overwrites --embed-thumbnail --add-metadata -i -o '/home/aa/Music/%(title)s.%(ext)s' -x -f bestaudio/best --audio-format mp3 $@
notify-send 'yt done'
