#!/bin/sh
# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Uses non default software
alias \
	find="fd" \
	ls="lsd --group-dirs first" \
	cat="bat" \
	fzf="fzf --preview=\"bat {} --color=always\"" \
	diff="diff-so-fancy" \

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -v" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	df="df -h"  \
	free="free -m"  \
	ffmpeg="ffmpeg -hide_banner" \
	# yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	la="ls -a" \
	l="ls -l" \
	lla="ls -la" \
	lt="ls --tree" \
	grep="grep --color=auto" \
	ccat="highlight --out-format=ansi" \

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	y="yay" \
	pi="pip install" \
	piu="pip install --user" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	SS="sudo systemctl" \
	S="systemctl --user" \
	shortcuts_st="grep 'static Shortcut shortcuts'  -A 1000 -m 1 ~/.dotfiles/st/config.h | grep '};' -m 1 -B 1000"  \
	o="xdg-open" \
	pc="pass -c" \
	q="exit" \


# This alias is important. It enables the `pauseallmpv` command.
alias mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)"

# Some other stuff
alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	weath="less -S ~/.local/share/weatherreport" \
	ipython="ipython --TerminalInteractiveShell.editing_mode=vi" \
	speedtest="curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -" \

,e() { du -a ~/.scripts/* ~/.config/* ~/.dotfiles/*(N) /var/lib/transmission/.config/*(N) | cut -d$'\t' -f2- | fzf | xargs  -r $EDITOR ;}
,t() { fzf | xargs -r -I % $EDITOR % ;}
cdf() { cd -- "$(du | cut -d$'\t' -f2- | fzf)"}

cdt() { cd -- "$HOME/Downloads/Torrent/$(/usr/bin/ls -C --format=single-column ~/Downloads/Torrent | fzf;)"}
