#!/bin/sh
# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Uses non default software
alias \
	cat="bat" \
	diff="diff-so-fancy" \
	find="fd" \
	fzf="fzf --preview=\"bat {} --color=always\"" \

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	df="df -h"  \
	ffmpeg="ffmpeg -hide_banner" \
	free="free -m"  \
	mkd="mkdir -pv" \
	mv="mv -iv" \
	rm="rm -v" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	rs="rsync -avP --update" \
	# yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \

# Colorize commands when possible.
alias \
	ccat="highlight --out-format=ansi" \
	grep="grep --color=auto" \

# These common commands are just too long! Abbreviate them.
alias \
	S="systemctl --user" \
	SS="sudo systemctl" \
	YT="youtube-viewer" \
	e="$EDITOR" \
	f="$FILE" \
	g="git" \
	ka="killall" \
	o="xdg-open" \
	p="sudo pacman" \
	pc="pass -c" \
	pi="pip install" \
	piu="pip install --user" \
	q="exit" \
	sc="source $XDG_CONFIG_HOME/zsh/.zshrc" \
	sve="source venv/bin/activate" \
	sdn="sudo shutdown -h now" \
	shortcuts_st="grep 'static Shortcut shortcuts'  -A 1000 -m 1 ~/.dotfiles/submodules/st/config.h | grep '};' -m 1 -B 1000"  \
	trem="transmission-remote" \
	v="$EDITOR" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	y="yay" \
	,gs="git status" \
	,gc="git commit" \
	,gch="git checkout" \
	,gcm="git commit -m" \
	,gfa="git fetch --all" \
	,gpl="git pull" \
	,gps="git push" \
	,ga="git add" \
	,gl="git log" \
	,gd="git diff" \
	,gds="git diff --staged" \
	,gcan="git commit --amend --no-edit" \
	,gpsf="git push --force" \
	,gr="git rebase" \
	,grc="git rebase --continue" \
	lt="tree -L 2" \
	ac="autorandr -c" \
	p1="ping 1.1.1.1" \
	xc="xclip -sel clip" \
	xcp="xclip -sel clip -target image/png -i" \
	kx="killall xcape" \
	fs='flameshot gui -r | tee ~/Pictures/Flameshot_$(date +%Y-%m-%d_%H-%M-%S).jpg | xcp' \
	/="ack" \


# This alias is important. It enables the `pauseallmpv` command.
alias mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)"

# Some other stuff
alias \
	ipy="ipython3 --TerminalInteractiveShell.editing_mode=vi" \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	speedtest="curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -" \
	weather="less -S ~/.local/share/weatherreport" \
	webtorrent="webtorrent -o $HOME/Downloads/Torrent --mpv" \


function vs() {
	nvim ~/.scripts/tools/$1
}
function rms() {
	mv -iv $1 ~/.local/share/Trash/files
}
function qe() {
	v ~/.local/share/qutebrowser_$1/config/custom_config.py
}

,e() { du --exclude-from=$HOME/.config/du_excludes  -a ~/.scripts/* ~/.config/* ~/.dotfiles/*(N) /var/lib/transmission/.config/*(N) | cut -d$'\t' -f2- | fzf | xargs -d '\n' -r $EDITOR ;}
,t() { fzf | xargs -d '\n' -r -I % $EDITOR % ;}
cdf() { cd -- "$(du | cut -d$'\t' -f2- | fzf)"}
cdp() { cd -- "$(/usr/bin/ls -C -d ~/dev/git/*(N) ~/dev/projects/*(N) ~/localstorage/dev/*(N) | fzf;)"}

cdt() { cd -- "$HOME/Downloads/Torrent/$(/usr/bin/ls -C --format=single-column ~/Downloads/Torrent | fzf;)"}
