#!/bin/sh

# This script move the selected window to the bottom left of the screen.
# The window will take up no more than a third of
# the width or height of the screen.
newwidth=$(($(xdotool getdisplaygeometry | awk '{print $1}')))
display_height=$(($(xdotool getdisplaygeometry | awk '{print $2}')))
newheight=$((($newwidth)*10/16))

xdotool getwindowfocus windowsize $newwidth $newheight

new_y=$((($display_height-$newheight)/2))
xdotool getwindowfocus windowmove 0 $new_y
