#!/bin/sh
lock() {
    # i3lock -t -i ~/.config/wall.png
    gnome-screensaver-command -l
    # scrot /tmp/screen_locked.png
    # convert /tmp/screen_locked.png -scale 10% -scale 1000% /tmp/screen_locked2.png
    # i3lock -i /tmp/screen_locked2.png
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
