#!/bin/bash

#changes window in fullscreen modus
# last=$(i3-msg -t get_tree | jq -e 'recurse(.nodes[]; .nodes) | select(.focused)')
# i3-msg "focus $1"
# cur=$(i3-msg -t get_tree | jq -e 'recurse(.nodes[]; .nodes) | select(.focused)')


if i3-msg -t get_tree | jq -e 'recurse(.nodes[]; .nodes) | select(.focused and .type=="con").fullscreen_mode == 1'
then i3-msg "fullscreen; focus $1"; i3-msg "fullscreen"
# then i3-msg "fullscreen; focus $1; fullscreen"
else i3-msg "focus $1"
fi
