#!/bin/sh
xrandr --output HDMI2 --off --output HDMI1 --primary --mode 1680x1050 --pos 0x0 --rotate normal --output DP1 --off --output eDP1 --mode 1368x768 --pos 1680x282 --rotate normal --output VIRTUAL1 --off
